<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Observable 剖析</title>
    <script src="https://code.jquery.com/jquery-3.1.0.js"></script>
    <script src="https://cdn.bootcss.com/rxjs/6.0.0-alpha.3/Rx.min.js"></script>
</head>
<body>
<div>
    <p>创建 Observables</p>
    <p>订阅 Observables</p>
    <p>执行 Observables</p>
    <p>清理 Observables</p>
</div>
<button id="addBtn">add</button>
<script>
    // Rx.Observable.create 是 Observable 构造函数的别名，它接收一个参数：subscribe 函数。
    // 下面的示例创建了一个 Observable，它每隔一秒会向观察者发送字符串 'hi' 。

    // var observable = Rx.Observable.create(function subscribe(observer) {
    //     var id = setInterval(() => {
    //         observer.next('hi')
    //     }, 1000);
    //     setTimeout(function () {
    //         clearInterval(id)
    //     }, 10000)
    // });
    function subscribe(observer) {
        var intervalID = setInterval(() => {
            observer.next('hi');
        }, 1000);

        return function unsubscribe() {
            clearInterval(intervalID);
        };
    }

    var unsubscribe = subscribe({next: (x) => console.log(x)});

    // 稍后：
    setTimeout(function () {
        unsubscribe(); // 清理资源
    },2000);

    // Observable 执行可以传递三种类型的值：
    // "Next" 通知： 发送一个值，比如数字、字符串、对象，等等。
    // "Error" 通知： 发送一个 JavaScript 错误 或 异常。
    // "Complete" 通知： 不再发送任何值。
    // "Next" 通知是最重要，也是最常见的类型：它们表示传递给观察者的实际数据。"Error" 和 "Complete" 通知可能只会在 Observable 执行期间发生一次，并且只会执行其中的一个。
    //
    // 这些约束用所谓的 Observable 语法或合约表达最好，写为正则表达式是这样的：
    // next * (error | complete) ?


    // 在 Observable 执行中, 可能会发送零个到无穷多个 "Next" 通知。如果发送的是 "Error" 或 "Complete" 通知的话，那么之后不会再发送任何通知了。
    // var observable = Rx.Observable.create(function subscribe(observer) {
    //     observer.next(1);
    //     observer.next(2);
    //     observer.next(3);
    //     observer.complete();
    //     observer.next(4); // 因为违反规约，所以不会发送
    // });
    // observable.subscribe(x => console.log(x));


    // 在 subscribe 中用 try/catch 代码块来包裹任意代码是个不错的主意，如果捕获到异常的话，会发送 "Error" 通知：
    // var observable = Rx.Observable.create(function subscribe(observer) {
    //     try {
    //         observer.next(1);
    //         observer.next(2);
    //         observer.next(3);
    //         observer.complete();
    //     } catch (err) {
    //         observer.error(err); // 如果捕获到异常会发送一个错误
    //     }
    // });
    // observable.subscribe(x => console.log(x));


    // 清理 Observable 执行
    // 因为 Observable 执行可能会是无限的，并且观察者通常希望能在有限的时间内中止执行，所以我们需要一个 API 来取消执行。因为每个执行都是其对应观察者专属的，
    // 一旦观察者完成接收值，它必须要一种方法来停止执行，以避免浪费计算能力或内存资源。

    var observable = Rx.Observable.from([10, 20, 30]);
    var subscription = observable.subscribe(x => console.log(x));
    // 稍后：
    subscription.unsubscribe();
</script>
</body>
</html>
